### ISSUE TITLE
Current Slack Export Format No Longer Has "user_profile"

### ISSUE THREAD

**Issue by JonnyTsGitHub** [thomasloupe/Slackord#11]
It appears that json exports from slack now (I've never tried before) do not have the "user_profile" property on messages.  Instead they have a "user" field which is just a key into a "users.json" which provides the profile info.

So in order to get the needed info you need to load that users.json, build a dictionary, and look up the key as you process each message.

My suggestion is that you provide an option in the Setup menu to specify the users.json which is then remembered across runs.

**Comment by thomasloupe** [comment]
Hi Jonny,

I had a look at my test Slack tenant, and exported JSON as of today. You might be looking at the wrong data as I'm seeing that channel content still contains a "text", "real_name", "display_name", and "name" in the JSON export.

For example, see the exported history from the attached file. Yours should be similar if you're looking at the file named after the channel. 

If you are willing to share one of your exports with personal info redacted, this could be very useful, as otherwise, I cannot reproduce this.
[2022-07-31.txt](https://github.com/thomasloupe/Slackord2/files/9228524/2022-07-31.txt)

**Comment by JonnyTsGitHub** [comment]
Yes, you're right.  This is my problem.

I was using a tool called backupery which allows exporting private channels and purports to export to the exact same format as slack.  However it drops this section.  This is what I originally assumed was the case, so before I opened this issue I went into my normal slack export and I THOUGHT I confirmed that it was missing there too. But when I checked today... its totally there.  So, I can only guess that I got confused between the identically named files.

So, yeah, sorry to waste your time.  :(

I still need this to work, but I can write the code myself since this is not a standard slack export I'm dealing with.

**Comment by JonnyTsGitHub** [comment]
Actually I found an even easier workaround than modding the code.  Slack will take the backupery format.  So import my export back as public channels, then use the standard slack export on those new public channel copies.  Slackord will take that output.  :)

**Comment by thomasloupe** [comment]
Glad to hear that you have it working as expected! Enjoy!
