### ISSUE TITLE
Doesn't run on MacOS

### ISSUE THREAD

**Issue by erstwhile** [thomasloupe/Slackord#14]
Hello
I'm trying to run Slackord 2 on my MacBook and getting the following error after installing the .NET 6.0 framework and running ./Slackord from the command ilne. 
```
You must install or update .NET to run this application.

App: /Users/tomgillis/Downloads/Slackord v2.2.0 osx-x64/Slackord
Architecture: x64
Framework: 'Microsoft.WindowsDesktop.App', version '6.0.0' (x64)
.NET location: /usr/local/share/dotnet

No frameworks were found.

Learn about framework resolution:
https://aka.ms/dotnet/app-launch-failed

To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.WindowsDesktop.App&framework_version=6.0.0&arch=x64&rid=osx.11.0-x64
```

**Comment by thomasloupe** [comment]
Hi @erstwhile,

It appears the dotnet6 version of Slackord for Mac and Linux is broken currently due to Winforms being used.
I have looked into this issue, even going so far as to port the application over to MAUI, but it is out of scope for the application at this time.

Instead I may release Slackord2 as a CLI application for Mac when I have the time in the next couple weeks.
For now, the only solution is to run the Windows version in a VM or emulator such as Wine, etc. I apologize for this, but due to the way Mac/Windows aren't compatible from a GUI drawing perspective, it is actually impossible to release Slackord2 as a mac app as long as it has a GUI written in Winforms.

I will assign this as a feature request to create the mac CLI version of Slackord2 and will do what I can to at least make the app native to mac, even if there's just a CLI and no GUI. You can use this issue to track the release of the Mac version of Slackord.

**Comment by thomasloupe** [comment]
Hi @erstwhile, see if the updated mac build [here](https://github.com/thomasloupe/Slackord2/releases/tag/v2.2.0) will work for you.

Please note the following has changed but I haven't updated the README yet:
1. You will need to put your bot's token in the `Token.txt` file.
2. You will need to place any JSON files you wish to send to Discord into the `Files` folder.
3. Watch the prompts when using Slackord2, and select the JSON file number you wish to parse and import to Discord.

Please let me know if you encounter any issues.

**Comment by thomasloupe** [comment]
I will leave this open for a week just in case you need some additional time. The README has been updated with specific instructions as well to use Slackord for Mac/Linux.

**Comment by jstane01** [comment]
Hi,
Sorry for my stupid question but how can I do to run Slackord.
I use MacOS I've download the last archive [Slackord.v2.2.0.osx-x64.zip] here : https://github.com/thomasloupe/Slackord2/releases

But when I open the ZIP I don't see executable file.

I’m sorry I’m a total novice...
For the moment I managed to install the BOT, I copied the TOKEN in Token.txt... but I don’t understand how to launch Slackcord, is it in the terminal?  

Thanks If you are agree to help me...
Julie

**Comment by thomasloupe** [comment]
Hi Julie,

Yes, first, you need to make sure you install dotnet 6 for Mac [here](https://dotnet.microsoft.com/en-us/download/dotnet/6.0). Be sure you select `.NET Runtime 6.0.8`, and download/install the `mac x64` release (not the .NET Desktop Runtime 6.0.8).

Download Slackord for Mac and extract it anywhere. Open a terminal and `chmod` all files within the Slackord directory to allow read/write access like this:
`chmod -R +rw "Slackord v2.2.0"`

Make sure your bot token is in `Token.txt` and you have a JSON file in the `Files` directory and you should be all set! Just double-click the file called `Slackord` or run it by entering the Slackord directory via terminal like so: 
`cd "Slackord v2.2.0"` (You can press `TAB` halfway through typing that and it should autocomplete so you can just press `ENTER`.)

Then just type:  `./Slackord`!
From then on out, all you need to do to run Slackord is either double-click the Slackord file in the directory, or run it from the Terminal using the `./Slackord` command.

**Comment by thomasloupe** [comment]
I have verified this works on MacOS Monterey version 12.5.1.
![image](https://user-images.githubusercontent.com/6563450/187279551-1a7ec027-02d6-46ec-93bb-33aa7dbdaf64.png)

I will go ahead and close this issue as completed.

**Comment by jstane01** [comment]
Dear Thomas,

Thank you for your help.
I installed .NET Runtime 6.0.8  x64 for Mac
![Download-NET-6-0-Linux-macOS-and-Windows-](https://user-images.githubusercontent.com/112414269/187475989-b9328e0c-98f6-4ffb-bfb1-d8d2adaf5ca9.png)
![Capture d’écran 2022-08-30 à 17 04 24](https://user-images.githubusercontent.com/112414269/187476050-318bcde5-cf49-4332-8d14-a100b32980d3.png)

I have JSON files in "Files" folder 
I have paste my toke in Token.txt
--> https://www.loom.com/share/5448cd9b0a764e4a914686e4fb600939

then I entered the command in the terminal:
`chmod -R +rw "Slackord v2.2.0"`

But that tells me: **chmod: Slackord v2.2.0: No such file or directory**
![Capture d’écran 2022-08-30 à 17 07 40](https://user-images.githubusercontent.com/112414269/187476108-4d80010d-7ee0-4e7a-bd39-699da549f7fa.png)


While the folder is present in "downloads".
Am I missing a step? 

(I’m on Monterey 12.2.1)

Thank you again if you are ok to help me

**Comment by thomasloupe** [comment]
Hi @erstwhile, make sure you are just outside of the directory when you run that command. The idea is that you need to change the permissions of the files so that they can be read/written to. In this command you are targeting the folder, so if you are in Terminal and the directory you are currently in doesn't show that folder, you are not in the directory above it.

For instance, if you downloaded Slackord 2.2.0, and placed and extracted it to `Downloads`, you would need to change your directory to `Downloads` via:
`cd Downloads`, then run the chmod command listed in the previous reply on the folder. You can verify you are in the correct directory by doing `ls` in the Terminal, and by seeing the `Slackord 2.2.0` directory listed.

If you would like me to help you walk through this, please send me a DM on Twitter.
