### ISSUE TITLE
Use slash commands instead of !slackord

### ISSUE THREAD

**Issue by jarommadsen** [thomasloupe/Slackord#24]
Discord has rolled out slash command support for bots. https://support.discord.com/hc/en-us/articles/1500000368501-Slash-Commands-FAQ#:~:text=WHAT%20ARE%20SLASH%20COMMANDS%3F,to%20use%20your%20favorite%20bot.

Have you looked into this yet? It'd be much cleaner than having `!slackord` strewn throughout the import.

**Comment by jarommadsen** [comment]
Btw, very happy to see this project especially since Slack has killed the free tier for small groups. Never hit the 10,000 message limit so cutting it back to 3 months was big slap to the face.

**Comment by thomasloupe** [comment]
I did investigate doing this, and may work toward migrating it to a slash command. Slackord2 is a bit older as a bot and was designed before message intents were "a thing". Now that they're mandatory, I may just consider doing this just to take a step out of the README to make things less complicated. Will need some additional time to consider, but it wouldn't be hard to implement since it's just a single triggered command.

**Comment by thomasloupe** [comment]
Enhancement accepted, though it will be some time before I can get around to it.

**Comment by thomasloupe** [comment]
Completed and released: https://github.com/thomasloupe/Slackord2/releases/tag/v2.2.4
