### ISSUE TITLE
Export from Backupery

### ISSUE THREAD

**Issue by mgoplerud** [thomasloupe/Slackord#27]
Hello! I am trying to use this tool to migrate a Slack export. I used Backupery ([here](https://www.backupery.com/products/backupery-for-slack/)) to do it as that can let me do private channels.

I had an issue where many messages were not being parsed. When I run this, I get no output for "Begin Parsing Json" and it seems like nothing is imported into Discord.

I include a `.json` below with two messages that I think illustrate the issue. 

The first one is from the simple Slack documentation on how to read its exports (e.g., [here](https://slack.com/help/articles/220556107-How-to-read-Slack-data-exports)). The second one is a sample one from Backupery. It seems that the only ones that are recognized are ones that attach files?

Thanks for your help!

```
[
	{
		"type": "message",
		"user": "U2147483697",
		"text": "Hello world",
		"ts": "1355517523.000005"
	},
  {
    "client_msg_id": "XX",
    "type": "message",
    "text": "Two versions are the same",
    "user": "XX",
    "ts": "XX",
    "team": "XX",
    "blocks": [
      {
        "type": "rich_text",
        "block_id": "1KUR",
        "elements": [
          {
            "type": "rich_text_section",
            "elements": [
              {
                "type": "text",
                "text": "Two versions are the same."
              }
            ]
          }
        ]
      }
    ]
  }
]
```

**Comment by thomasloupe** [comment]
Hi, @mgoplerud!

Slackord2 does not support unofficial methods for exporting Slack chat history. This is mostly because the JSON these tools create are usually wildly different than what is expected by Slackord2. There are no plans to support Backupery at this time. Though I believe [slackdump](https://github.com/rusq/slackdump) exports work natively with Slackord2. I am not sure if it handles private channels, but it handles DMs and threads.

The other solution would be to simply modify the JSON formatting to work for Slackord2.

See Issue: #15.

**Comment by mgoplerud** [comment]
Thanks!
