### ISSUE TITLE
Multiple JSONs?

### ISSUE THREAD

**Issue by 3h50** [thomasloupe/Slackord#4]
So its exporting day by day for each channel.  Feature request for selecting multiple JSONs? :D

**Comment by 3h50** [comment]
I made this in Node to just merge all dates of a channel.  https://gist.github.com/mrarmyant/2a998404a0575378b23d0b741087954b

**Comment by thomasloupe** [comment]
@mrarmyant Please see point 3 of the following: https://github.com/thomasloupe/Slackord2#important-please-read.
I will still consider the request, as I know it can be painful for larger Slack server imports.

**Comment by 3h50** [comment]
Wow I missed like one of 30 lines.  Lol.  No worries!  I see why on a massive file it got to the end and cancelled due to some that didn't get parsed.  Does it always kill the job if some are unsuccessful?  I assumed its more likely I'm just breaking all sorts of memory bounds.

**Comment by thomasloupe** [comment]
If they are unsuccessful, yes, it'll kill the task - mostly because the assumption is that you'd want that data in-line (and in timestamp) with the rest of your data versus reparsing and adding to the end. If you have any red in the debug window, check your JSON file, or read the error message if there is one. 

It could also be that you're likely breaking the 2000 char limit enforced by Discord. In that case, you'd want to break the JSON up into multiple files. This is another reason why I didn't support multi-JSON imports. I'm sure you can see the rabbit hole there. I'm sure there are ways of getting all that working in harmony, but it's quite a lot for me to take on at the moment.

EDIT: I should mention that Slackord2 understands the latter case and will let you know in the debug window if your JSON message outputs will exceed the 2000 char limit.

**Comment by 3h50** [comment]
Well no, I get not parsing it to one file, its huge and unmaintainable.  Queuing up other files though to start jobs next does make sense.  Slack is backing up individual days for each channel, times 15 channels, each with 2.5 years of open source cnc development lol.  A lot of days, and if the import fails you go to discord and delete line by line.

We are just trying to save old data we have lost anyway from autorunning. It its too large it could just be thrown out.  This is a case where some searchable data is better than no searchable data

**Comment by thomasloupe** [comment]
@mrarmyant I think the "skip failed message" task seems appropriate rather than failing out. I'll see what I can do about that.

For the multiple JSON file imports, I'll have a look into how I can best parse multiple JSONS within a folder. If it's not a crazy rewrite of a bunch of functions for me, I'll also work on getting that in, but no promises.

**Comment by 3h50** [comment]
I rolled back the number of files I was merging and it accepted it.  It would get to the end, be fine, then turn red.  Didn't see any errors when it was red other than it saying failure.  I imagine I escaped the bounds of something that no one was supposed to break lol

**Comment by thomasloupe** [comment]
Would you be willing to send me that debug window when that happened? Feel free to mark out any entries that may contain any PII if need be, and send over to thomasgloupe@gmail.com. I'd love to have a look and see if there's something I can spot or improve there.

**Comment by thomasloupe** [comment]
While I didn't implement parsing ability for multiple JSON files, I did fix your second issue by creating a new feature to allow bypassing of messages that exceed the 2000 character limit for Discord. Please see the following feature request for [2.0.7](https://github.com/thomasloupe/Slackord2/issues/5).
