### ISSUE TITLE
When first trying to run on Mac, mac gets stuck in a chain of permission errors

### ISSUE THREAD

**Issue by michaeldawson** [thomasloupe/Slackord#45]
When attempting to first run this program on Mac (Ventura 13.0.1), Mac goes to great lengths to make it impossible to run. Every individual library that is required causes a security exception that needs to be manually overwritten, after the program crashes.

Here's a video demonstrating this: https://drive.google.com/file/d/1cZUH-tBvqwytKpUGc8unFKyf_OxRB2e7/view?usp=sharing

Is it possible to bundle this up as a Mac App? I'd buy you a beer if we could get this working! 🙏 

(By the way, this issue is possible to overcome, by manually allowing security exceptions about 20 times, and restarting the program about 5 times. After doing so, there are no more security exceptions, but the program is failing for me for other reasons https://github.com/thomasloupe/Slackord2/issues/44)

**Comment by thomasloupe** [comment]
I've done a couple things to help soothe the issue here.
1. I've packaged Slackord2 for Mac as a single file, so now permissions only need to be granted to Slackord and the Files folder. This should greatly cut down on the amount of files needing security exceptions through mac.
2. I will look into packaging this as a mac app, but the last time I checked on this, it required that I pay Apple a yearly $200 fee perpetually for a developer license to prove that my app wasn't malware. I have no plans to do this now, or in the near future. I would greatly consider it if it were a one-time fee, but since my projects are always free, that's just not something I wish to consider.

Please grab the latest release for mac, which now contains a single file and a pdb debugging file, along with the Files folder instead of all the dependencies as well and let me know if that has made this painful process a bit easier for you. If so, I will continue to release updates this way going forward. My test Mac experiment resulted in me only needing to permit a single file instead of 20-30+ files now.

**Comment by michaeldawson** [comment]
Yeah no-one wants to be spending $200 for that! Amazing, and thanks for the super fast responses, too. I'll give this a shot on the weekend 🙌

**Comment by thomasloupe** [comment]
Hey @michaeldawson,

How'd it go? Just checking in before closing this off.

**Comment by thomasloupe** [comment]
Marking this one as completed.
