### ISSUE TITLE
Sorry, there's nothing to post because no JSON file was parsed prior to sending this command.

### ISSUE THREAD

**Issue by alegat** [thomasloupe/Slackord#50]
Hi Thomas, thank you for all the work you put for Slackord. I am struggling to make it work. Everything seems to work fine until I get the error "Sorry, there's nothing to post because no JSON file was parsed prior to sending this command."

I am using Slackord v2.4.3.6 and running on Mac OS 13.2.
I have exported my whole Slack workspace, both using the built-in Slack feature and with Slackdump.
I put a few .json files in the "Files" directory and run Slackord.
Then I write '/slackord' on Discord, but the bot answers "Sorry, there's nothing to post because no JSON file was parsed prior to sending this command."
In the Terminal, I get "Received a command to post messages to Discord, but no JSON file was parsed prior to receiving the command."

Any idea on what I am missing?
Thanks :-)

**Comment by thomasloupe** [comment]
Hi @alegat, the best way to find out what's happening is to download the source and debug the app as you run it, but if you're unable to do that, the next best thing would be to upload a zip of your export to Google Drive and reach out to me on Twitter or other social media with a Google Drive or cloud link to download and test your export.

The error is pretty generic in that it means exactly what it says - your JSON files weren't processed so there's nothing to post. This is likely due to some bad formatting with the JSON but there's only one way to know and that's to test it if possible.

**Comment by thomasloupe** [comment]
Quick question:

Have you put the folders in the Slackord2 Files directory?
Like so:
```
Folder
--Folder1
----FileName1.json
----FileName2.json
```
Slackord2 doesn't support this so, what happens if you instead take the files from the first folder and copy them to the Files directory for Slackord2?

The structure should look like this:
```
Folder
--FileName1.json
--FileName2.json
...
```

You would need to do this for each folder. I know this is a pain, but try and let me know.

**Comment by alegat** [comment]
Hi Thomas, I tried both but I got the error in both cases 😕

**Comment by thomasloupe** [comment]
Are you able to try this on a Windows machine by chance?
On the Windows version I am seeing no issues.

**Comment by thomasloupe** [comment]
@alegat Could you please try the latest version of Slackord for Mac/Linux and let me know how it goes?

Thanks!

**Comment by alegat** [comment]
Hi Thomas, thanks a lot for your help. At last I just manually saved the important data I needed.
But still, thanks for your great support!
Best :-)

**Comment by thomasloupe** [comment]
No problem at all, I'll go ahead and close the issue off. Thanks for the update and best of luck!
