### ISSUE TITLE
@mentions users by username and not by ID

### ISSUE THREAD

**Issue by junihey** [thomasloupe/Slackord#91]
The users are mentioned with @ in the slack-messages are shown with the ID like "U36NACXK5" and not with their real slack user-name

**Comment by thomasloupe** [comment]
Can you provide an example of where this happened with a full message?

**Comment by davidvess** [comment]
Hi @thomasloupe, I spent the day yesterday playing with Slackdump and your wonderful, Slackord.  I haven't messed with things at the command line level since library school but did very well.   I serve on the board of an open access journal about user experience research in libraries.  We've used slack since 2018 to do our work.  Of course, we're having to leave it because we can't access our work history anymore.  I've got it all now in Discord thanks to you and the creators of Slackdump.  I've actually used Slackdump and Slackord a bunch yesterday to play around with imports.  This means a lot to us and I'm sending you some love in the form of some $ here in a sec too!!  (If anyone out there is reading this, you should do the same. ) 

Anyway, I have the same issue that @junihey describes above.  Attached are images of two examples. I'm happy to share my export files or add you to my discord if you're curious about this little issue.  The fact that images shared in Slack messages didn't carry over in the migration (I'm gonna check this space not about that issue and also over at Slackdump), or that the at symbols reverted to the attached is a shame, but not a big deal.  I'm just happy to have our archive somewhere else.  

Best, David 

![Example of At Symbol Code 2](https://github.com/thomasloupe/Slackord/assets/400528/b20b9f9c-8500-46dc-a6d3-d8f1052142ef)
![Example of At Symbol Code 1](https://github.com/thomasloupe/Slackord/assets/400528/ebc548b3-94cc-461b-9b30-cb6b921ec5ca)

**Comment by thomasloupe** [comment]
Got it.

I think I'm aware of this one. It appears to only happen in scenarios where the user has joined the channel. Can you confirm that for me?

**Comment by davidvess** [comment]
Hey! Thanks for having a look.  I took a few screen grabs in different contexts.  The first (wide image) is from posts in a channel's main area.  The second one, (tall image) is from replies (in a thread) to posts in another channel.  If that makes sense?  I also verified that the strings are just stand-ins for our handles.  I can do a search and see that <@UG6KA9HTQ> stands for my handle which is normally my first and last name.  I also see that this is happening in all 13 channels in posts made by any user, not just me and the other two people, whose posts I used in the screen shots.  BTW, for what it's worth, I migrated channels in batches to respect the limits Slackdump states.   Thank you so much for having a look! 

![At Symbol Example in Regular Posts 1](https://github.com/thomasloupe/Slackord/assets/400528/5483bea3-418c-4ee1-862d-30256d185a5e)
![At Symbol Example in Regular Posts 2](https://github.com/thomasloupe/Slackord/assets/400528/8f2d4815-434d-4b8e-867e-65ca601c6f2d)

**Comment by FrenkLoonen** [comment]
This is what the JSON would look like. The tagged user is isolated in the rich_text_section elements:
```
        "type": "message",
        "text": "Hi there <@ABC12XY3Z45>, mail to <mailto:mail@domain.com|mail@domain.com> for more information :handshake:",
        "blocks": [
            {
                "type": "rich_text",
                "elements": [
                    {
                        "type": "rich_text_section",
                        "elements": [
                            {
                                "type": "text",
                                "text": "Hi there "
                            },
                            {
                                "type": "user",
                                "user_id": "ABC12XY3Z45"
                            },
                            {
                                "type": "text",
                                "text": ", mail to "
                            },
                            {
                                "type": "link",
                                "url": "mailto:mail@domain.com",
                                "text": "mail@domain.com"
                            },
                            {
                                "type": "text",
                                "text": " for more information "
                            },
                            {
                                "type": "emoji",
                                "name": "handshake",
                                "unicode": "1f91d"
                            }
                        ]
                    }
                ]
            }
        ],
```

**Comment by thomasloupe** [comment]
I believe I have fixed this in the new beta branch, which will release to main soon.
Please feel free to open another issue if you re-encounter this once 4.3.0 releases, and reference this issue!
